// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeriesManagerServer.Data.Services.SeriesManagerDataContext;

namespace SeriesManagerServer.Data.Services.Migrations
{
    [DbContext(typeof(SeriesManagerContext))]
    partial class SeriesManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SeriesManagerServer.Data.SeriesManagerData.Comics", b =>
                {
                    b.Property<long>("ComicsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComicsName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ComicsId");

                    b.ToTable("Comics");

                    b.HasData(
                        new { ComicsId = 1L, ComicsName = "Doomsday Clock" },
                        new { ComicsId = 2L, ComicsName = "The Life of Captain Marvel" },
                        new { ComicsId = 3L, ComicsName = "Tony Stark Iron Man" },
                        new { ComicsId = 4L, ComicsName = "Spider-geddon" }
                    );
                });

            modelBuilder.Entity("SeriesManagerServer.Data.SeriesManagerData.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ApiId");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("SeriesId");

                    b.ToTable("Series");

                    b.HasData(
                        new { SeriesId = 1, ApiId = 7194L, SeriesName = "13 Reasons Why" },
                        new { SeriesId = 2, ApiId = 31339L, SeriesName = "A Discovery of Witches" },
                        new { SeriesId = 3, ApiId = 3949L, SeriesName = "A series of unfortunate events" },
                        new { SeriesId = 4, ApiId = 31L, SeriesName = "Agents of S.H.I.E.L.D." },
                        new { SeriesId = 5, ApiId = 12036L, SeriesName = "Altered Carbon" },
                        new { SeriesId = 6, ApiId = 3182L, SeriesName = "American Gods" },
                        new { SeriesId = 7, ApiId = 4L, SeriesName = "Arrow" },
                        new { SeriesId = 8, ApiId = 919L, SeriesName = "Attack on Titan" },
                        new { SeriesId = 9, ApiId = 2540L, SeriesName = "Avengers Assemble" },
                        new { SeriesId = 10, ApiId = 22084L, SeriesName = "Ben 10" },
                        new { SeriesId = 11, ApiId = 21142L, SeriesName = "Big Hero 6 The Series" },
                        new { SeriesId = 12, ApiId = 20683L, SeriesName = "Black Lightning" },
                        new { SeriesId = 13, ApiId = 57L, SeriesName = "Blackish" },
                        new { SeriesId = 14, ApiId = 1855L, SeriesName = "Blindspot" },
                        new { SeriesId = 15, ApiId = 49L, SeriesName = "Brooklyn Nine-Nine" },
                        new { SeriesId = 16, ApiId = 25414L, SeriesName = "Castle Rock" },
                        new { SeriesId = 17, ApiId = 25242L, SeriesName = "Castlevania" },
                        new { SeriesId = 18, ApiId = 15307L, SeriesName = "Cloak and Dagger" },
                        new { SeriesId = 19, ApiId = 25110L, SeriesName = "Condor" },
                        new { SeriesId = 20, ApiId = 15L, SeriesName = "Constantine" },
                        new { SeriesId = 21, ApiId = 1369L, SeriesName = "Daredevil" },
                        new { SeriesId = 22, ApiId = 1851L, SeriesName = "Dcs Legends of Tomorrow" },
                        new { SeriesId = 23, ApiId = 210L, SeriesName = "Doctor Who" },
                        new { SeriesId = 24, ApiId = 2368L, SeriesName = "Dragon Ball Super" },
                        new { SeriesId = 25, ApiId = 133L, SeriesName = "Elementary" },
                        new { SeriesId = 26, ApiId = 1824L, SeriesName = "Fear The Walking Dead" },
                        new { SeriesId = 27, ApiId = 23314L, SeriesName = "Final Space" },
                        new { SeriesId = 28, ApiId = 20003L, SeriesName = "Freedom Fighters The Ray" },
                        new { SeriesId = 29, ApiId = 3022L, SeriesName = "Future Man" },
                        new { SeriesId = 30, ApiId = 82L, SeriesName = "Game of Thrones" },
                        new { SeriesId = 31, ApiId = 31257L, SeriesName = "God Friended Me" },
                        new { SeriesId = 32, ApiId = 11L, SeriesName = "Gotham" },
                        new { SeriesId = 33, ApiId = 28366L, SeriesName = "Grown-ish" },
                        new { SeriesId = 34, ApiId = 2476L, SeriesName = "Guardians of the Galaxy" },
                        new { SeriesId = 35, ApiId = 21216L, SeriesName = "Happy" },
                        new { SeriesId = 36, ApiId = 36768L, SeriesName = "Happy Together" },
                        new { SeriesId = 37, ApiId = 7L, SeriesName = "Homeland" },
                        new { SeriesId = 38, ApiId = 2300L, SeriesName = "Into The Badlands" },
                        new { SeriesId = 39, ApiId = 2175L, SeriesName = "Iron Fist" },
                        new { SeriesId = 40, ApiId = 1589L, SeriesName = "iZombie" },
                        new { SeriesId = 41, ApiId = 1370L, SeriesName = "Jessica Jones" },
                        new { SeriesId = 42, ApiId = 12522L, SeriesName = "Justice League Action" },
                        new { SeriesId = 43, ApiId = 11918L, SeriesName = "Kong King of the Apes" },
                        new { SeriesId = 44, ApiId = 3082L, SeriesName = "Krypton" },
                        new { SeriesId = 45, ApiId = 41L, SeriesName = "Last Man Standing" },
                        new { SeriesId = 46, ApiId = 6393L, SeriesName = "Legion" },
                        new { SeriesId = 47, ApiId = 5495L, SeriesName = "Lethal Weapon" },
                        new { SeriesId = 48, ApiId = 8898L, SeriesName = "Lost in Space" },
                        new { SeriesId = 49, ApiId = 1859L, SeriesName = "Lucifer" },
                        new { SeriesId = 50, ApiId = 2174L, SeriesName = "Luke Cage" },
                        new { SeriesId = 51, ApiId = 5511L, SeriesName = "MacGyver" },
                        new { SeriesId = 52, ApiId = 32819L, SeriesName = "Magnum P I" },
                        new { SeriesId = 53, ApiId = 12888L, SeriesName = "Man with a plan" },
                        new { SeriesId = 54, ApiId = 31365L, SeriesName = "Manifest" },
                        new { SeriesId = 55, ApiId = 2176L, SeriesName = "Marvels The Defenders" },
                        new { SeriesId = 56, ApiId = 324L, SeriesName = "Masterchef" },
                        new { SeriesId = 57, ApiId = 3160L, SeriesName = "MasterChef Australia" },
                        new { SeriesId = 58, ApiId = 417L, SeriesName = "MasterChef Junior" },
                        new { SeriesId = 59, ApiId = 80L, SeriesName = "Modern Family" },
                        new { SeriesId = 60, ApiId = 1871L, SeriesName = "Mr Robot" },
                        new { SeriesId = 61, ApiId = 488L, SeriesName = "Naruto Shippuden" },
                        new { SeriesId = 62, ApiId = 590L, SeriesName = "Pokemon" },
                        new { SeriesId = 63, ApiId = 3144L, SeriesName = "Preacher" },
                        new { SeriesId = 64, ApiId = 216L, SeriesName = "Rick and Morty" },
                        new { SeriesId = 65, ApiId = 34300L, SeriesName = "Rise of the Teenage Mutant Ninja Turtles" },
                        new { SeriesId = 66, ApiId = 5262L, SeriesName = "Riverdale" },
                        new { SeriesId = 67, ApiId = 20172L, SeriesName = "Runaways" },
                        new { SeriesId = 68, ApiId = 22188L, SeriesName = "Salvation" },
                        new { SeriesId = 69, ApiId = 14612L, SeriesName = "Santa Clarita Diet" },
                        new { SeriesId = 70, ApiId = 2158L, SeriesName = "Shadowhunters" },
                        new { SeriesId = 71, ApiId = 335L, SeriesName = "Sherlock" },
                        new { SeriesId = 72, ApiId = 143L, SeriesName = "Silicon Valley" },
                        new { SeriesId = 73, ApiId = 21928L, SeriesName = "Spider-Man" },
                        new { SeriesId = 74, ApiId = 713L, SeriesName = "SpongeBob SquarePants" },
                        new { SeriesId = 75, ApiId = 7480L, SeriesName = "Star Trek Discovery" },
                        new { SeriesId = 76, ApiId = 36483L, SeriesName = "Star Wars Resistance" },
                        new { SeriesId = 77, ApiId = 2993L, SeriesName = "Stranger things" },
                        new { SeriesId = 78, ApiId = 17862L, SeriesName = "Stretch Armstrong and the Flex Fighters" },
                        new { SeriesId = 79, ApiId = 1850L, SeriesName = "Supergirl" },
                        new { SeriesId = 80, ApiId = 19L, SeriesName = "Supernatural" },
                        new { SeriesId = 81, ApiId = 33395L, SeriesName = "Take Two" },
                        new { SeriesId = 82, ApiId = 6L, SeriesName = "The 100" },
                        new { SeriesId = 83, ApiId = 34017L, SeriesName = "The Adventures of Kid Danger" },
                        new { SeriesId = 84, ApiId = 66L, SeriesName = "The Big Bang Theory" },
                        new { SeriesId = 85, ApiId = 37675L, SeriesName = "The Dragon Prince" },
                        new { SeriesId = 86, ApiId = 36449L, SeriesName = "The Epic Tales of Captain Underpants" },
                        new { SeriesId = 87, ApiId = 13L, SeriesName = "The Flash" },
                        new { SeriesId = 88, ApiId = 25948L, SeriesName = "The Gifted" },
                        new { SeriesId = 89, ApiId = 17078L, SeriesName = "The Grand Tour" },
                        new { SeriesId = 90, ApiId = 35839L, SeriesName = "The Neighborhood" },
                        new { SeriesId = 91, ApiId = 20263L, SeriesName = "The Orville" },
                        new { SeriesId = 92, ApiId = 16544L, SeriesName = "The Punisher" },
                        new { SeriesId = 93, ApiId = 28134L, SeriesName = "The Purge" },
                        new { SeriesId = 94, ApiId = 32938L, SeriesName = "The Rookie" },
                        new { SeriesId = 95, ApiId = 14116L, SeriesName = "The Tick" },
                        new { SeriesId = 96, ApiId = 4296L, SeriesName = "The Tom and Jerry Show" },
                        new { SeriesId = 97, ApiId = 73L, SeriesName = "The Walking Dead" },
                        new { SeriesId = 98, ApiId = 1878L, SeriesName = "Thunderbirds are go" },
                        new { SeriesId = 99, ApiId = 8873L, SeriesName = "Timeless " },
                        new { SeriesId = 100, ApiId = 27557L, SeriesName = "Titans" },
                        new { SeriesId = 101, ApiId = 38387L, SeriesName = "Transformers Cyberverse" },
                        new { SeriesId = 102, ApiId = 7523L, SeriesName = "Van Helsing" },
                        new { SeriesId = 103, ApiId = 15296L, SeriesName = "Voltron Legendary Defender" },
                        new { SeriesId = 104, ApiId = 1371L, SeriesName = "Westworld" },
                        new { SeriesId = 105, ApiId = 689L, SeriesName = "Young Justice" },
                        new { SeriesId = 106, ApiId = 26020L, SeriesName = "Young Sheldon" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
